### ISSUE TITLE
Unclear what to do regarding the OAuth "Consent Screen"

### ISSUE THREAD

**Issue by yfarjoun** [MarkEdmondson1234/googleCloudRunner#102]
When I follow the instructions regarding getting a "Client ID file", I open the URL and am blocked:

![image](https://user-images.githubusercontent.com/2745554/104394031-c737e200-5513-11eb-9704-3b72144b5617.png)

If I try to configure the "Consent Screen" I'm further blocked, as I would like to use the "Internal" option, but this is limited to GSuite users:

![image](https://user-images.githubusercontent.com/2745554/104394126-f6e6ea00-5513-11eb-8198-43d57beacb8e.png)

If I select the external option it says it will only be available to "Test" users. should I do that and list myself as a test user? (or maybe I'll be allowed automatically?)

**Comment by yfarjoun** [comment]
Additionally, when I finally created an OAuth Client, I got the following note that seems worrying, but perhaps isn't:

![image](https://user-images.githubusercontent.com/2745554/104394899-85a83680-5515-11eb-849f-7c2309ec3026.png)

**Comment by yfarjoun** [comment]
I don't know if this is related to the issue above, so I'm keeping it in the same issue....sorry for the possible mess.

I managed to get all 5 checkmarks, but then the configuration of the various services fails:

```
> cr_setup()
ℹ ==Welcome to googleCloudRunner v0.3.0 setup==
This wizard will scan your system for setup options and help you with any that are missing. 
Hit 0 or ESC to cancel. 

1: Configure/check all googleCloudRunner settings
2: Configure GCP Project Id
3: Configure Authentication JSON file
4: Configure Cloud Storage bucket
5: Configure Cloud Run region
6: Configure Cloud Scheduler build email
7: Configure Cloud Build service account

Selection: 1
──────────────────────────────────────────────────────────────────────────────────────────────────
Do you want to configure for all R sessions or just this project? 

1: All R sessions (Recommended)
2: Project only

Selection: 1
──────────────────────────────────────────────────────────────────────────────────────────────────
✓ Found: GCE_DEFAULT_PROJECT_ID=[secure]
──────────────────────────────────────────────────────────────────────────────────────────────────
✓ Found: GCE_AUTH_FILE=[secure]/[secure]-a182080e608e.json
──────────────────────────────────────────────────────────────────────────────────────────────────
✓ Found: GCS_DEFAULT_BUCKET=[secure]_for_cloud_runner
──────────────────────────────────────────────────────────────────────────────────────────────────
✓ Found: CR_REGION=us-east1
──────────────────────────────────────────────────────────────────────────────────────────────────
✓ Found: CR_BUILD_EMAIL=googlecloudrunner@[secure].iam.gserviceaccount.com
──────────────────────────────────────────────────────────────────────────────────────────────────
ℹ The Cloud Build service account ([secure]@cloudbuild.gserviceaccount.com) will need permissions during builds for certain operations calling other APIs.  This is distinct from the local authentication file you have setup.
What services do you want to setup for the Cloud Build service account? (Esc or 0 to skip) 

1: Skip or something not listed below
2: All of the below (Recommended)
3: Cloud Run deployments
4: Secret Manager
5: BigQuery operations
6: Cloud Storage operations

Selection: 2
ℹ Configuring [secure]@cloudbuild.gserviceaccount.com for Cloud Run deployments
ℹ 2021-01-13 02:01:31 > Setting client.id from [secure]/client_secret_[secure]-art1l8op11kafoee3eus5d3b6985kquh.apps.googleusercontent.com.json
ℹ 2021-01-13 02:01:32 > Checking existing roles
ℹ 2021-01-13 02:01:32 > Request Status Code:  403
Error: API returned: The caller does not have permission
> 
```

**Comment by MarkEdmondson1234** [comment]
Yes it all looks fine apart from the first step of downloading the client.id, which is a new setup Google's end I think.  You should add yourself as a test user of the service email if thats an option, I will try it again myself soon to see.  As I guess it should be only you using the GCP client its fine to keep it on testing mode forever.

**Comment by MarkEdmondson1234** [comment]
I have gone through set up again and got some screenshots for the documentation, let me know if the below helps:

It is recommended to use a new Google Cloud Project, to ensure all modern services are activated.  Billing will need to be enabled with a credit card.

You will need to be logged in as the Owner of the project for the below.

Once your project is created, visit `APIs & Services > Credentials` or `https://console.cloud.google.com/apis/credentials` to set up an OAuth 2.0 Client ID

<img width="874" alt="oauth-create-credentials-start" src="https://user-images.githubusercontent.com/3155884/104427113-284ace80-5583-11eb-9319-c9744e1a553f.png">

If not created already, you will first need to make an OAuth consent screen at `APIs & Services > OAuth consent screen` or
`https://console.cloud.google.com/apis/credentials/consent`

<img width="692" alt="oauth-consent-screen-name-step1" src="https://user-images.githubusercontent.com/3155884/104427153-3567bd80-5583-11eb-8ac9-d5ac763e832d.png">

For most purposes, you will only need to authorize your own email through this OAuth consent screen, in which case the settings you want will be

* User type = "External" (or optionally "Internal" if you are a GSuite user)

* Scopes - you can skip this for now as it can be added later via `cr_setup()` or the manual setup instructions below.  As the app will not be public, the app should not require verification

<img width="657" alt="oauth-consent-screen-scopes-step2" src="https://user-images.githubusercontent.com/3155884/104427213-44e70680-5583-11eb-85ce-852a3a22b79a.png">

* Test users = "your@email.com" (plus anyone else who will authenticate with same client ID)

<img width="631" alt="oauth-consent-screen-test-user-step3" src="https://user-images.githubusercontent.com/3155884/104427277-59c39a00-5583-11eb-9739-d5c618989a13.png">

* Publishing status = "Testing"

<img width="715" alt="oauth-consent-screen-final-app" src="https://user-images.githubusercontent.com/3155884/104427323-63e59880-5583-11eb-9107-74e9fd9a4c0d.png">

You DO NOT need to push to production.  If it is, turn it back to testing.

<img width="795" alt="oauth-consent-screen-push-to-production" src="https://user-images.githubusercontent.com/3155884/104427412-7c55b300-5583-11eb-8b8d-bd0fca390c80.png">

Once the consent screen is configured, you should be able to create credentials at `APIs & Services > Credentials > Create Credentials > OAuth client ID` or `https://console.cloud.google.com/apis/credentials/oauthclient` 

<img width="874" alt="oauth-create-credentials-start" src="https://user-images.githubusercontent.com/3155884/104427552-a909ca80-5583-11eb-9c97-f75c3678e541.png">

Select "Desktop app" - an OAuth client should be created.  

<img width="628" alt="oauth-create-credentials-desktop-app" src="https://user-images.githubusercontent.com/3155884/104427474-942d3700-5583-11eb-8064-d6284bcfc283.png">

Download this client ID via the download button on the far right.

<img width="870" alt="oauth-create-credentials-download-clientid" src="https://user-images.githubusercontent.com/3155884/104427455-8d9ebf80-5583-11eb-87ca-0198c2ae20cf.png">

Once you have the client Id JSON file, you should be able to use the below to setup the rest of the configuration such as service accounts, scopes and

**Comment by MarkEdmondson1234** [comment]
@yfarjoun  I think your issue is the scopes for the app.  There is a bug in GCP console mislabelling it as BigQuery

> Scopes - this needs to be set as .../auth/cloud-platform - "View and manage your data across Google Cloud Platform services". It is currently mislabelled as "BigQuery API" in the GCP console - bug filed with them

**Comment by MarkEdmondson1234** [comment]
I also found an error that would have prevented it working for you in my test setup due to changes at Google's end, ( https://github.com/MarkEdmondson1234/googleCloudRunner/issues/89 ) so if you can try with the latest GitHub version it should be possible to complete all the tests

**Comment by yfarjoun** [comment]
@MarkEdmondson1234 Thank-you for your detailed instructions. I'll follow them tonight and see where we go. in case you are interested, I'm trying to set-up a live covid-19 plot using your googleCloudRunner...the manual version is here: https://chart-studio.plotly.com/~yfarjoun/3/ 

👍

**Comment by yfarjoun** [comment]
```
── Test summary ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
ℹ Cloud Build Docker deployment successful
ℹ Cloud Run plumber API deployment successful
ℹ Cloud Run plumber API Pub/Sub deployed successfully
ℹ Cloud Build R scripts deployed successfully
ℹ Scheduled Cloud Build R scripts deployed successfully
✓ Deployment tests complete!
```

However....I did have to turn on these APIs that you listed at the bottom of your long comment above, and I manually added roles to the cloudbuild service account as for some reason the cr_setup() function was not able to do it.

Thanks for your patience and hand-holding....I'm off to see if I can schedule my job!

🎉
