### ISSUE TITLE
Can't use custom container with cr_deploy_r()

### ISSUE THREAD

**Issue by dvergari** [MarkEdmondson1234/googleCloudRunner#111]
Hello,
I'm trying to deploy an R script with a custom docker image on GCP using cr_deploy_r().
I'm running the following code:

`cr_deploy_r("script.R", r_image="eu.gcr.io/my-project/my-r-image:latest")`

the image is already pushed to the google repository.

In the build log I see that it tries to pull **rocker/**eu.gcr.io/my-project/my-r-image:latest

> starting build "0d58c652-7b3a-4d01-b967-914955c28c48"
>
>FETCHSOURCE
>BUILD
>Pulling image: rocker/eu.gcr.io/my-project/my-r-image:latest
>Error response from daemon: pull access denied for rocker/eu.gcr.io/my-project/my-r-image, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

Am I doing something wrong?

Thanks you in advance.

sessionInfo()

>R version 3.6.3 (2020-02-29)
>Platform: x86_64-pc-linux-gnu (64-bit)
>Running under: Ubuntu 18.04.5 LTS
>
>Matrix products: default
>BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
>LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1
>
>locale:
> [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8        LC_COLLATE=C.UTF-8    
> [5] LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8    LC_PAPER=C.UTF-8       LC_NAME=C             
> [9] LC_ADDRESS=C           LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   
>
>attached base packages:
>[1] stats     graphics  grDevices utils     datasets  methods   base     
>
>other attached packages:
>[1] shiny_1.6.0                  googleAuthR_1.3.1.9000       googleCloudRunner_0.4.1.9000
>
>loaded via a namespace (and not attached):
 >[1] zip_2.1.1                 Rcpp_1.0.6                compiler_3.6.3           
 >[4] bslib_0.2.4               later_1.1.0.1             jquerylib_0.1.3          
 >[7] tools_3.6.3               digest_0.6.27             jsonlite_1.7.2           
>[10] memoise_2.0.0             gargle_0.5.0              lifecycle_1.0.0          
>[13] rlang_0.4.10              cli_2.3.0                 rstudioapi_0.13          
>[16] curl_4.3                  yaml_2.2.1                fastmap_1.1.0            
>[19] httr_1.4.2                googleCloudStorageR_0.6.0 xml2_1.3.2               
>[22] fs_1.5.0                  sass_0.3.1                askpass_1.1              
>[25] glue_1.4.2                R6_2.5.0                  purrr_0.3.4              
>[28] magrittr_2.0.1            usethis_2.0.1             promises_1.2.0.1         
>[31] htmltools_0.5.1.1         ellipsis_0.3.1            assertthat_0.2.1         
>[34] mime_0.10                 jose_1.0                  xtable_1.8-4             
>[37] httpuv_1.5.5              miniUI_0.1.1.1            openssl_1.4.3            
>[40] cachem_1.0.4

**Comment by MarkEdmondson1234** [comment]
The prefix is not expecting eu.gcr (it only looks for "gcr.io") - so if you set it yourself via prefix = "" and r_image="eu.gcr.io/my-project/my-r-image:latest" or prefix="eu.gcr.io/my-project/", r_image="my-r-image:latest"

**Comment by dvergari** [comment]
thanks you very much, it works!
