### ISSUE TITLE
cr_setup_test()

### ISSUE THREAD

**Issue by featherduino** [MarkEdmondson1234/googleCloudRunner#118]
Hi Mark, thanks for creating such an awesome package, it really strengthens the R community up top.

While setting this up and testing i am facing an error : 403 
The API does not have sufficient permissions

![image](https://user-images.githubusercontent.com/17808683/120042663-282a0780-c028-11eb-8f7b-e4e68b9faf60.png)

**Comment by featherduino** [comment]
Pretty sure my roles and permissions are right 
![image](https://user-images.githubusercontent.com/17808683/120044974-940e6f00-c02c-11eb-8e0c-282a13aa0780.png)

**Comment by MarkEdmondson1234** [comment]
Thank you!

The error suggests the cloud storage bucket role is not active. The lookup functions show what roles you need but not what you have active. 

If you run cr_setup() again to check, see what the bucket settings return in particular.

**Comment by featherduino** [comment]
hey thanks
however the cr_setup only checks for the 5 variables, i have all of them authenticated
and for bucket 
![image](https://user-images.githubusercontent.com/17808683/120067186-eafd5e00-c097-11eb-8432-0066e9815b4f.png)

**Comment by featherduino** [comment]
hey i think i got it can pass 3 tests, it was a service account setup issue

Getting this issue with the cloudrun setup

**Comment by MarkEdmondson1234** [comment]
Did you run all the setup functions?  It looks like some GCP settings are not live yet.  If you share the full logs of the Cloud Run we could narrow down which ones.

**Comment by featherduino** [comment]
hey yeah sure so this is the exact spot 
![image](https://user-images.githubusercontent.com/17808683/121419593-c18edd00-c989-11eb-9f12-4d75134b5dbf.png)

**Comment by MarkEdmondson1234** [comment]
I think this was related to this issue https://github.com/MarkEdmondson1234/googleCloudRunner/issues/141 so it should be fixed if you try the latest version from GitHub?
