### ISSUE TITLE
Unable to install dev version due to typo in DESCRIPTION file

### ISSUE THREAD

**Issue by smach** [MarkEdmondson1234/googleCloudRunner#127]
FYI running this 

`remotes::install_github("MarkEdmondson1234/googleCloudRunner")`

Generates this error:

    Error: Failed to install 'googleCloudRunner' from GitHub:
      Missing commas separating Remotes: 'MarkEdmondson1234/googleAuthR
      r-lib/gargle'

Possibly a missing comma in the DESCRIPTION file here?

    Remotes:
      MarkEdmondson1234/googleAuthR
      r-lib/gargle

(At work so can't really fork the repo to test and do a pull request right now, sorry)

**Comment by MarkEdmondson1234** [comment]
Woops!  And its even patched in https://github.com/MarkEdmondson1234/googleCloudRunner/pull/125 but I hadn't merged, so its merged now.  Thanks for heads up.
