### ISSUE TITLE
Is it possible to add an argument for kaniko_cache = TRUE to cr_deploy_plumber?

### ISSUE THREAD

**Issue by dcaud** [MarkEdmondson1234/googleCloudRunner#132]
I've got a build that is taking a long time. It seems one way to speed up re-builds is to cache. Any ideas on how to make that work?

**Comment by MarkEdmondson1234** [comment]
The kaniko cache applies to Docker containers, if that's a long build you can add the flag to the Docker build step so the second build speeds up. 

Order of commands in your Docker container also matters, try to put commands that change more often later in the build eg the R script copy into the build. 

You can also try building an intermediate container in another build that you FROM for your plumber script.

**Comment by dcaud** [comment]
Thanks for the tips. It seems some of the caching is already happening (via whatever Cloud Build does), but I will investigate some of your tips.

**Comment by MarkEdmondson1234** [comment]
If all you are changing is the R script it should only take a couple of minutes.

**Comment by dcaud** [comment]
I'm not quite sure how the caching works -- but on the first re-build in a couple months, the whole docker image had to be rebuilt. However, subsequent re-builds used Google's caching. Maybe the first re-build I did had something odd with it. Either way, things work well at the moment.

**Comment by MarkEdmondson1234** [comment]
The cache default timeout is 2 weeks.  You can configure that with cache-ttl if working with directly
https://cloud.google.com/build/docs/kaniko-cache#configuring_the_cache_expiration_time

2 weeks sounds about right though, as the dependencies have probably changed in that time period.  If you want to fix the Docker image in that state, tag it and use that tag for your Docker pulls, not :latest (default when no tag)

**Comment by MarkEdmondson1234** [comment]
And yes, I've looked to add `kaniko_cache=TRUE` to all the deployment functions that depend on the `cr_buildstep_docker()` function.
