### ISSUE TITLE
CloudRun fails with ERROR: expected one argument

### ISSUE THREAD

**Issue by engti** [MarkEdmondson1234/googleCloudRunner#141]
Issue, when running _cr_setup_test()_ I get the following error

![image](https://user-images.githubusercontent.com/1890066/139829385-b23411e5-350a-4ae7-beb2-3bc62ee4f07e.png)

And when I looked at the GCP logs I found the following:

`Step #0 - "deploy cloudrun": Digest: sha256:fdd975aa13e7321672d13909089a33160ad1e3e25a5ee9c00dc9a91213cd93c1
Step #0 - "deploy cloudrun": Status: Downloaded newer image for gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
Step #0 - "deploy cloudrun": gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
Step #0 - "deploy cloudrun": ERROR: (gcloud.run.deploy) argument --image: expected one argument
Step #0 - "deploy cloudrun": Usage: gcloud run deploy [[SERVICE] --namespace=NAMESPACE] [optional flags]`

**Comment by MarkEdmondson1234** [comment]
Hmm thanks will check it, perhaps the `gcloud run` has changed from beta.

**Comment by MarkEdmondson1234** [comment]
Thanks for the report, I was able to replicate it. 

For some reason the image name was not coming back in the builds return object, so I've put in a more reliable method of determining the image name.  Running `cr_setup_test()` option 3 now succeeds with the GitHub version installed via `remotes::install_github("MarkEdmondson1234/googleCloudRunner")` and in the next CRAN release.
