### ISSUE TITLE
Default Pubsub Message?

### ISSUE THREAD

**Issue by muschellij2** [MarkEdmondson1234/googleCloudRunner#166]
Does it make sense to make `Sys.time` or some other meaningful message the default instead of the topic name as in:
https://github.com/MarkEdmondson1234/googleCloudRunner/blob/075aff754cf8191cde5f3f0894c2fba8c7062bf0/R/cloudbuild_schedule.R#L167

**Comment by MarkEdmondson1234** [comment]
I wanted a way for the build to know which topic is sending the data, if it's activated by many PubSub topics. That way it can react in different ways, perhaps.
