### ISSUE TITLE
`cr_jwt_create` returns `Error : parse error: premature EOF`

### ISSUE THREAD

**Issue by brancengregory** [MarkEdmondson1234/googleCloudRunner#171]
I'm working with the following setup:

I have a successfully authenticated project and build script which deploys two cloud run services. One is a private docker API and the other is a public shinydashboard.

I'm attempting to secure a JWT and token within the deployed dashboard so I can use `cr_jwt_with_httr` to make authenticated calls to the plumber API. The dashboard is auto-authenticating with `credential_service_account`.

Any ideas? Have I misunderstood the process?

**Comment by MarkEdmondson1234** [comment]
Perhaps I need to see some code, but the function needs a json client to pick up the clientId to create the JWT token, is that in place?

**Comment by MarkEdmondson1234** [comment]
I think it may be as you can auth automatically with credentials so it's not picking up the json client id that it assumes is in GAR_CLIENT_JSON env arg? It may be you can find the auto auth one via code but it's not supported as is, quickest would be to also upload with the app the client json (it's not sensitive data)

**Comment by brancengregory** [comment]
Yep, including the client json with the dashboard did the trick. Thanks!

**Comment by MarkEdmondson1234** [comment]
Great, sounds like a cool setup would like to see some details if appropriate :)
