### ISSUE TITLE
Error: http_400 Invalid project resource name projects/ProjectName

### ISSUE THREAD

**Issue by alpha-wise** [MarkEdmondson1234/googleCloudRunner#194]
Hi,

I just manage to setup a GCP project using `cr_setup()` function without any errors. But when I run `cr_setup_test()`, I got an error that says the project name is invalid. I couldn't find a solution for this and appreciate if you can suggest me a direction.

=============================
Final output of `cr_setup()` function:

i 2022-07-16 02:33:41 > Checking existing roles
√ The Cloud Build service account (xxx@cloudbuild.gserviceaccount.com) has Cloud Build Access.
√ The Cloud Build service account (xxx@cloudbuild.gserviceaccount.com) has Secret Manager Access.
√ The Cloud Build service account (xxx@cloudbuild.gserviceaccount.com) has Cloud Run Access.
√ The Cloud Build service account (xxx@cloudbuild.gserviceaccount.com) has Cloud Storage Access.
√ The Cloud Build service account (xxx@cloudbuild.gserviceaccount.com) has all recommended roles
----------------------------------------------------------------------------------------------------------------------------------------------
√ Setup complete! You can test it with cr_setup_test()

========================
Output of `cr_setup_test()` function:

-- Attempting Docker deployment on Cloud Build via cr_deploy_docker() --

i 2022-07-16 02:34:06 > Dockerfile found in D:/R/R-4.0.2/library/googleCloudRunner/example - using it and ignoring dockerfile argument

-- # Deploy docker build for image: gcr.io/tradingapi/example --------------------------------------------------------------------------------

-- # Uploading D:/R/R-4.0.2/library/googleCloudRunner/example to gs://gcrptradingbucket/example.tar.gz ---------------------------------------
i 2022-07-16 02:34:06 > Tarring files in tmpdir:
* api.R
* Dockerfile
* server.R
i 2022-07-16 02:34:06 > Uploading example.tar.gz to gcrptradingbucket/example.tar.gz
i 2022-07-16 02:34:06 > File size detected as  874 bytes
i 2022-07-16 02:34:06 > Request Status Code:  400
! http_400 Cannot insert legacy ACL for an object when uniform bucket-level access is enabled. Read more at https://cloud.google.com/storage/docs/uniform-bucket-level-access - Retrying with predefinedAcl='bucketLevel'
i 2022-07-16 02:34:06 > File size detected as  874 bytes
i 2022-07-16 02:34:07 > StorageSource available for builds in directory: /workspace/deploy
i 2022-07-16 02:34:07 > See ?cr_buildstep_source_move for a buildstep to move files into /workspace/
i 2022-07-16 02:34:07 > Request Status Code:  400
Error: http_400 Invalid project resource name projects/TradingAPI

**Comment by MarkEdmondson1234** [comment]
I think it is as it says that the name you have chosen for the bucket or project name isn't allowed for some reason. Can you try another name? Perhaps try in the GCP console first to check

**Comment by alpha-wise** [comment]
Thanks a lot Mark. I changed the name and it worked. The confusing thing was I never get any error from the GCP console as well as `cs_setup()` function. Thanks
