### ISSUE TITLE
Image tags update due to Docker client

### ISSUE THREAD

**Issue by brancengregory** [MarkEdmondson1234/googleCloudRunner#196]
Per the Cloud Build changelog (https://cloud.google.com/build/docs/release-notes) and associated documentation (https://cloud.google.com/build/docs/interacting-with-dockerhub-images#working_with_docker_client_versions), the docker push command must be passed the `-a` flag to push all image tags. Otherwise only the `latest` tag will be applied

**Comment by MarkEdmondson1234** [comment]
Ah cool! I have some logic in to build and push multiple Docker tags, this makes it simpler to achieve.
