### ISSUE TITLE
Error in curl::handle_setopt with cr_deploy_run

### ISSUE THREAD

**Issue by lgnbhl** [MarkEdmondson1234/googleCloudRunner#208]
Hello Mark

Thanks a lot for the package. I got the following error message when pushing an update of an locally R Shiny app file on Cloud Run using `cr_deploy_run()`:

```r
Error in curl::handle_setopt(handle, .list = req$options): Option seekfunction (20167) has unknown or unsupported type.
```

Any idea how to solve this?

Thanks a lot!
Félix

**Comment by MarkEdmondson1234** [comment]
Hmm sorry this looks like a lower level issue within curl, not seen it before myself. Could you ask on their repo linking to this issue so I can follow it?

**Comment by lgnbhl** [comment]
The issue was due to the use of an older version of the curl R package. It was simply fixed running `install.packages("curl")`. Sorry about that!

**Comment by MarkEdmondson1234** [comment]
Ok cool! No worries
