### ISSUE TITLE
Schedule an R script - Environment variables?

### ISSUE THREAD

**Issue by j450h1** [MarkEdmondson1234/googleCloudRunner#38]
Does this use case mentioned [here](https://code.markedmondson.me/googleCloudRunner/articles/cloudscheduler.html) support the use of environment variables somehow? I usually have them set in the .Renviron file (which of course is .gitignored). What is your suggestion?

**Comment by MarkEdmondson1234** [comment]
Hi Jas :) Yes you can add environment arguments to a cloud build step or to the entire cloud build via the env argument.


________________________________

**Comment by j450h1** [comment]
Hi Mark and thanks for the quick response! I was hoping to maybe add .Renviron file as an argument or similar, but I guess it's not a huge LOE to copy them all over one by one by using ```Sys.getenv```. Seems a bit meta, but I'll give it a try.

**Comment by MarkEdmondson1234** [comment]
You could include a step to download an .Renviron file if you prefer from cloud storage via gsutil or the new google secrets service on gcloud


________________________________

**Comment by MarkEdmondson1234** [comment]
And referencing your other issue, you could also include a source that has your .Renviron file in it.


________________________________

**Comment by MarkEdmondson1234** [comment]
But I think that’s over complicating it, you don’t need to add extra code to read the env vars. Copy the entries as in your local .Renviron into the env arguments for the build and they are available to R as if you were running locally.


________________________________
