### ISSUE TITLE
cr_deploy_r - Error: API returned - unable to resolve source

### ISSUE THREAD

**Issue by j450h1** [MarkEdmondson1234/googleCloudRunner#39]
Hi Mark! Me again. I'm going through the toy example you provided. I've already completed the setup steps mentioned [here](https://code.markedmondson.me/googleCloudRunner/articles/setup.html) However, I get this error. Is this because I don't have permission to this particular **RepoSource**?  Do you have instructions on what type of **RepoSource** should be put here? I don't really follow what this source is actually doing or its purpose. What is meant by "_runs against a source_"?

To be clear, I do understand the process of mirroring a Github repo to a Google Cloud Source repository, but just don't know what repo I should be mirroring if not this one called googleCloudStorageR which is a different R package???

```
> library(googleCloudRunner)
> 
> # this can be an R filepath or lines of R read in from a script
> r_lines <- c("list.files()",
+              "library(dplyr)",
+              "mtcars %>% select(mpg)",
+              "sessionInfo()")
> 
> # example code runs against a source that is a mirrored GitHub repo
> source <- cr_build_source(RepoSource("googleCloudStorageR",
+                                      branchName = "master"))
> # check the script runs ok
> cr_deploy_r(r_lines, source = source)
2020-02-01 02:31:04> Deploy R script cr_rscript_2020021580553064023104 to Cloud Build
2020-02-01 02:31:04> Request Status Code: 400
Error: API returned: unable to resolve source
```

**Comment by MarkEdmondson1234** [comment]
The source is optional, it’s if you have files that you would like to run your commands against into the workspace. Yes this example is using my own access as a demo.  See the use cases section of the website for some examples with and without a source.

You can skip the source if everything is included with the docker containers that you need, or you perhaps include a step to download data from somewhere else (like cloud storage)


________________________________

**Comment by j450h1** [comment]
Got it. Makes perfect sense! I resolved as you recommended by skipping the source. I guess your point with including the source in this particular example was to execute ```list.files()``` which presumably shows the contents of the files in the root of the googleCloudStorage repo.

**Comment by j450h1** [comment]
A bit premature, looks like a got a different error now. Anyway to help debug?

``` r
library(googleCloudRunner)
#> Setting scopes to https://www.googleapis.com/auth/cloud-platform
#> Successfully auto-authenticated via ***

# this can be an R filepath or lines of R read in from a script
r_lines <- c("list.files()",
             "library(dplyr)",
             "mtcars %>% select(mpg)",
             "sessionInfo()")

# check the script runs ok
cr_deploy_r(r_lines)
#> 2020-02-01 22:10:48> Deploy R script cr_rscript_2020021580623848221048 to Cloud Build
#> 2020-02-01 22:10:49> Cloud Build started - logs: 
#> https://console.cloud.google.com/gcr/builds/2ee75d50-f13b-4061-998c-143977d9afd3?project=843223677839
#> 
#> Waiting for build to finish:
#>  |=================| Build finished
#> 2020-02-01 22:12:14> Build finished with status: SUCCESS
#> ==CloudBuildObject==
#> buildId:  2ee75d50-f13b-4061-998c-143977d9afd3 
#> status:  SUCCESS 
#> logUrl:  https://console.cloud.google.com/gcr/builds/2ee75d50-f13b-4061-998c-143977d9afd3?project=843223677839 
#> timeout:  600s 
#> logsBucket:  gs://843223677839.cloudbuild-logs.googleusercontent.com 
#> steps:
#> $`1`
#> ==cloudRunnerBuildStep==
#> name: rocker/verse
#> args:
#> - Rscript
#> - -e
#> - |-
#>   list.files()
#>   library(dplyr)
#>   mtcars %>% select(mpg)
#>   sessionInfo()
#> id: cr_rscript_2020021580623848221048
#> 
#> source:
#>  Named list()

# schedule the script once its working  
cr_deploy_r(r_lines, schedule = "15 21 * * *")
#> 2020-02-01 22:12:14> Deploy R script cr_rscript_2020021580623934221214 to Cloud Build
#> 2020-02-01 22:12:14> Scheduling R script on cron schedule: 15 21 * * *
#> 2020-02-01 22:12:15> Request Status Code: 400
#> Error: API returned: Request contains an invalid argument.
```

<sup>Created on 2020-02-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by MarkEdmondson1234** [comment]
Can you review the website’s Google Cloud setup steps, such as adding your Cloud Build service email as a user of Cloud Scheduler?


________________________________

**Comment by j450h1** [comment]
Yes, I have done that and double checked the instructions. In addition, I created this additional service account. Still getting the same error.

"_If you get the error using Cloud Scheduler with a HTTP target of “**Request contains an invalid argument**” then ensure you have a service email with service-{project-number}@gcp-sa-cloudscheduler.iam.gserviceaccount.com with Cloud Scheduler Service Agent role. This is only needed if you created the project before March 2019. This only needs to exist in the GCP project, it is not used in deployment - create another service key for that. See here_"

![image](https://user-images.githubusercontent.com/7351530/73606069-2a2aa600-455b-11ea-974d-4829d8c0aaae.png)

* **Done** 
---------------------------------------------------------------------------------------------------
"_The Cloud Build service account needs permissions if you want it to deploy to Cloud Run: This can be set here where you enable Cloud Run Admin and Service Account User roles. More details found at this Google reference article._"

![image](https://user-images.githubusercontent.com/7351530/73606010-2f3b2580-455a-11ea-9d74-f8d88b698ecc.png)

* I've added BigQuery Admin as per: If you want to use BigQuery services in your builds, give your build email BigQuery IAM access
* I've added Cloud Scheduler Admin although the instructions don't mention that.
-------------------------------------------------------------------------------------------------
"_A service auth key needs Cloud Storage Admin, Cloud Build Editor, Cloud Run Admin, Cloud Scheduler Admin roles to use all the functions in the package - this key can be downloaded and used for auth via GCE_AUTH_FILE"_

Here are the IAM settings for the service account associated with the GCE_AUTH_FILE:

![image](https://user-images.githubusercontent.com/7351530/73606050-d61fc180-455a-11ea-802f-477285f90095.png)

**Comment by MarkEdmondson1234** [comment]
Ok its a Google setup auth issue but just to be sure can you rerun with `options(googleAuthR.verbose=2)` which should output something like this:

```r
Body JSON parsed to: {"httpTarget":{"body":"eyJzdGVwcyI6W3sibmFtZSI6InJvY2tlci92ZXJzZSIsImFyZ3MiOlsiUnNjcmlwdCIsIi1lIiwibGlzdC5maWxlcygpXG5saWJyYXJ5KGRwbHlyKVxubXRjYXJzICU+JSBzZWxlY3QobXBnKVxuc2Vzc2lvbkluZm8oKSJdLCJpZCI6ImNyX3JzY3JpcHRfMjAyMDAyMTU4MDYzNjMwMDEwMzgyMCJ9XSwidGltZW91dCI6IjYwMHMifQ==","oauthToken":{"serviceAccountEmail":"cloudrunner@projectid.iam.gserviceaccount.com"},"uri":"https://cloudbuild.googleapis.com/v1/projects/project-id/builds","httpMethod":"POST"},"description":"cr_rscript_2020021580636300103820","name":"projects/project-id/locations/europe-west1/jobs/cr_rscript_2020021580636300103820","schedule":"15 21 * * *"}
```

**Comment by j450h1** [comment]
Sure, let me give that a try.

**Comment by j450h1** [comment]
_Update:_

1. Some additional IAM permissions need to be added for the cloudbuild service account (843223677839@cloudbuild.gserviceaccount.com) or else you get the error as per below:

```
> options(googleAuthR.verbose=2) 
> 
> library(googleCloudRunner)
Setting scopes to https://www.googleapis.com/auth/cloud-platform
2020-02-02 01:50:51> Auto-auth - json
Successfully auto-authenticated via ***
> 
> # this can be an R filepath or lines of R read in from a script
> r_lines <- c("list.files()",
+              "library(dplyr)",
+              "mtcars %>% select(mpg)",
+              "sessionInfo()")
> 
> # check the script runs ok
> cr_deploy_r(r_lines)
2020-02-02 01:50:51> Deploy R script cr_rscript_2020021580637051015051 to Cloud Build
2020-02-02 01:50:51> Token exists.
2020-02-02 01:50:51> Request: https://cloudbuild.googleapis.com/v1/projects/jas-test/builds/
2020-02-02 01:50:51> Body JSON parsed to: {"steps":[{"name":"rocker/verse","args":["Rscript","-e","list.files()\nlibrary(dplyr)\nmtcars %>% select(mpg)\nsessionInfo()"],"id":"cr_rscript_2020021580637051015051"}],"timeout":"600s"}
2020-02-02 01:50:52> Request Status Code: 403
2020-02-02 01:50:52> API returned error: service account "843223677839@cloudbuild.gserviceaccount.com" has insufficient permission to execute the build on project "***"
```
As a temporary workaround, I just provided it with Project Editor permissions and I can proceed further for now. If you know what specific permissions, I can change that.

![image](https://user-images.githubusercontent.com/7351530/73606400-bdb1a600-455e-11ea-81c0-2b40aa388368.png)


2.  Now it fails as usual here:

```
> # schedule the script once its working  
> cr_deploy_r(r_lines, schedule = "15 21 * * *")
2020-02-02 01:54:35> Deploy R script cr_rscript_2020021580637275015435 to Cloud Build
2020-02-02 01:54:35> Scheduling R script on cron schedule: 15 21 * * *
2020-02-02 01:54:35> Token exists.
2020-02-02 01:54:35> Request: https://cloudscheduler.googleapis.com/v1/projects/jas-test/locations/us-central1/jobs/
2020-02-02 01:54:35> Body JSON parsed to: {"httpTarget":{"body":"eyJzdGVwcyI6W3sibmFtZSI6InJvY2tlci92ZXJzZSIsImFyZ3MiOlsiUnNjcmlwdCIsIi1lIiwibGlzdC5maWxlcygpXG5saWJyYXJ5KGRwbHlyKVxubXRjYXJzICU+JSBzZWxlY3QobXBnKVxuc2Vzc2lvbkluZm8oKSJdLCJpZCI6ImNyX3JzY3JpcHRfMjAyMDAyMTU4MDYzNzI3NTAxNTQzNSJ9XSwidGltZW91dCI6IjYwMHMifQ==","oauthToken":{"serviceAccountEmail":"843223677839@cloudbuild.gserviceaccount.com"},"uri":"https://cloudbuild.googleapis.com/v1/projects/{PROJECT_NAME_REDACTED}/builds","httpMethod":"POST"},"description":"cr_rscript_2020021580637275015435","name":"projects/{PROJECT_NAME_REDACTED}/locations/us-central1/jobs/cr_rscript_2020021580637275015435","schedule":"15 21 * * *"}
2020-02-02 01:54:35> Request Status Code: 400
2020-02-02 01:54:35> API returned error: Request contains an invalid argument.
2020-02-02 01:54:35> No retry attempted: Request contains an invalid argument.
Error: API returned: Request contains an invalid argument.
```

**Comment by MarkEdmondson1234** [comment]
I had a similar issue the first time I tried it, and I ended up making the special cloudrunner@ service account (see my request JSON) I note you are using the default cloudbuilder email so I think that is the issue. The email set in the environment arg should be a special service account setup with the permissions you need, which is in addition to the default cloud builder email which I think is only needed for internal Cloud Build use.

**Comment by MarkEdmondson1234** [comment]
And for now make sure this is all happening in the same project to keep it simple

**Comment by j450h1** [comment]
* Everything is indeed in the same project

* I managed to get it working!

Here are the steps I took:

* Created this service account and set this environment variable
```CR_BUILD_EMAIL=cloudrunner@{PROJECT_NAME}.iam.gserviceaccount.com```

* Download the JSON service account key for this new account and update the path for the environment variable ```GCE_AUTH_FILE```

Here are the IAM permissions for this account:

![image](https://user-images.githubusercontent.com/7351530/73635023-66bbd780-4617-11ea-9238-2564a9b67807.png)

Thanks for helping me troubleshoot!

**Comment by MarkEdmondson1234** [comment]
Great :) I think I’ll add a check to enforce making your own service account and not reuse the Build email as it makes sense to use that one but doesn’t seem to work (bug?). I could also add a premade build that creates the service account.


________________________________

**Comment by j450h1** [comment]
Just one more question, am I able to view the output of the R code somewhere? The logs?

![image](https://user-images.githubusercontent.com/7351530/73637172-81447f80-461c-11ea-8238-8a4dc553b191.png)

**Comment by MarkEdmondson1234** [comment]
Yes all builds are in the Cloud Build history, including scheduled ones.


________________________________

**Comment by j450h1** [comment]
Thinking through this some more.... I never actually tried the combination of pointing to JSON key for: 843223677839@cloudbuild.gserviceaccount.com for ```GCE_AUTH_FILE```  **AND** setting it as the ```CR_BUILD_EMAIL``` so I think in theory it could work as long as both environment variables are related to the same service account and the same permissions I showed, if that makes sense.

**Comment by MarkEdmondson1234** [comment]
Yeah there are a few authentications to confuse:

- auth to push builds to cloud build/scheduler from local R session
- auth for the script to do its stuff, possibly re-using default cloud build email
- auth for Cloud scheduler to be allowed to push builds

It’s simpler if first and last is the same but not necessary.


________________________________

**Comment by j450h1** [comment]
Got it makes sense! Thanks again!
