### ISSUE TITLE
timeout not used if specified in cr_build_yaml()

### ISSUE THREAD

**Issue by MarkEdmondson1234** [MarkEdmondson1234/googleCloudRunner#43]
This should work?

```r
cr_build_yaml(steps, 
              timeout = 3600,
              options = list(machineType = 'N1_HIGHCPU_8'))
```

**Comment by dmoimpact** [comment]
Unfortunately the output ignores the settings at the current moment:
![image](https://user-images.githubusercontent.com/46580892/75634240-36faf200-5c0c-11ea-9321-892cd0616c1c.png)

**Comment by MarkEdmondson1234** [comment]
@dmoimpact what code are you using to try to generate the build?

**Comment by MarkEdmondson1234** [comment]
This seems to work:

```r
cr_build(
  cr_build_yaml(steps = cr_buildstep_docker("my-image"), 
                options = list(machineType = "N1_HIGHCPU_8"))
)
```

<img width="270" alt="Screenshot 2020-03-01 at 22 55 36" src="https://user-images.githubusercontent.com/3155884/75634642-ca81f200-5c0f-11ea-9522-26ba9c28dad0.png">

**Comment by dmoimpact** [comment]
```
scheduleR <- cr_build_yaml(
  steps = c(
    cr_buildstep(...
)))

my_build <- cr_build_make(scheduleR)
schedule_build <- cr_build(my_build,timeout = "3600s",options = list(machineType ='N1_HIGHCPU_8'))
```

(I tried with, and without "" in the seconds.)

**Comment by MarkEdmondson1234** [comment]
You can specify the option at build time or when you make the yaml, but they both seem to work for me:

```
cr_build(
  cr_build_yaml(steps = cr_buildstep_docker("my-image")), 
  options = list(machineType = "N1_HIGHCPU_8")
)
```

<img width="279" alt="Screenshot 2020-03-01 at 23 03 30" src="https://user-images.githubusercontent.com/3155884/75634779-e043e700-5c10-11ea-84d4-2789b3aaa33d.png">
)

**Comment by MarkEdmondson1234** [comment]
Ok I think its about timeout not the option?

In which case yes it currently doesn't respect the timeout if its in `cr_build_yaml()`, only if its in `cr_build_make()` or cr_build()`:

```r
cr_build_make(cr_build_yaml(cr_buildstep_docker("my-image"), 
               timeout = 500,
               options = list(machineType = 'N1_HIGHCPU_8')), timeout = 777)
#==CloudBuildObject==
#timeout:  777s 
#steps:
#- name: gcr.io/cloud-builders/docker
#  args:
# ...
```

**Comment by MarkEdmondson1234** [comment]
Should be fixed in latest version:

```r
cr_build_make(cr_build_yaml(cr_buildstep_docker("my-image"), 
              timeout = 500,
              options = list(machineType = 'N1_HIGHCPU_8')))
# ==CloudBuildObject==
# timeout:  500s 
# steps:

**Comment by dmoimpact** [comment]
Great, I will try it our. Thanks!
