### ISSUE TITLE
Can't deploy shiny apps with cr_deploy_r()

### ISSUE THREAD

**Issue by axel-analyst** [MarkEdmondson1234/googleCloudRunner#44]
Hi Mark,
UPDATED.
With R shiny apps I meant RStudio Addin. I am just refer to https://code.markedmondson.me/googleCloudRunner/articles/cloudscheduler.html#schedule-an-r-script I cannot run any option to just schedule the script. I just want to schedule the script.

When I run the code:

 `cr_deploy_r('searchconsole.R', schedule = '6 5 * * *', r_image = 'gcr.io/gcer-public/googleauthr-verse')`

with RStudio Addin (`googleCloudRunner::cr_deploy_gadget()` ), I receive the error:
```
2020-02-24 12:14:32> Request Status Code: 400
2020-02-24 12:14:32> API returned error: Request contains an invalid argument.
2020-02-24 12:14:32> No retry attempted: Request contains an invalid argument.
Error: API returned: Request contains an invalid argument.
```
I double checked the issue with roles, but my project and members were created after May 2019 and all:
http://my.jetscreenshot.com/demo/20200224-snai-77kb.jpg

What else it could be? Because I tried almost everythin with auth and roles potential issues. Thank you in advance.

sessioninfo():
```
R version 3.6.2 (2019-12-12)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] LC_COLLATE=Russian_Russia.1251  LC_CTYPE=Russian_Russia.1251    LC_MONETARY=Russian_Russia.1251
[4] LC_NUMERIC=C                    LC_TIME=Russian_Russia.1251    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_1.4.0                googleCloudStorageR_0.5.1  googleCloudRunner_0.1.1    googleAuthR_1.1.1         
[5] searchConsoleR_0.4.0       googleComputeEngineR_0.3.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3       magrittr_1.5     xtable_1.8-4     R6_2.4.1         rlang_0.4.4      fastmap_1.0.1   
 [7] httr_1.4.1       globals_0.12.5   tools_3.6.2      parallel_3.6.2   miniUI_0.1.1.1   htmltools_0.4.0 
[13] askpass_1.1      openssl_1.4.1    yaml_2.2.1       assertthat_0.2.1 digest_0.6.23    gargle_0.4.0    
[19] zip_2.0.4        later_1.0.0      promises_1.1.0   fs_1.3.1         codetools_0.2-16 curl_4.3        
[25] mime_0.9         memoise_1.1.0    glue_1.3.1       compiler_3.6.2   jsonlite_1.6.1   future_1.16.0   
[31] httpuv_1.5.2     listenv_0.8.0   

```

**Comment by MarkEdmondson1234** [comment]
You can't use `cr_deploy_r()` to publish Shiny apps - Shiny apps need a Shiny server running and need websockets and certain ports open etc.  The potential solution is to use Cloud Run via `cr_deploy_run()` but this is unsupported at the moment until the issues on https://github.com/MarkEdmondson1234/googleCloudRunner/issues/35 are resolved.

**Comment by axel-analyst** [comment]
UPDATED.
With R shiny apps I meant RStudio Addin. I am just refer to https://code.markedmondson.me/googleCloudRunner/articles/cloudscheduler.html#schedule-an-r-script I cannot run any option to just schedule the script. I just want to schedule the script.

**Comment by MarkEdmondson1234** [comment]
Ok cool - I would check the Google setup steps here for creating the service account - I don't see a custom service email created in your screenshot of Google IAM
https://code.markedmondson.me/googleCloudRunner/articles/setup.html

The error returned isn't helpful, but it is usually because the email Cloud Scheduler has been given is the build email, not your auth email, and the build email does not have authorization.

**Comment by axel-analyst** [comment]
Thanks, it seems the issue but I am sure I understood correctly. I created the email and set it, but it did not work. I just simplified the script to '1+1' so it will not be definetly the scheduled script issue.

I used 111-compute@developer.gserviceaccount.com as my service account and formed JSON for auth with it. Do I need to give all roles and form JSON auth within service account with custom service email (scheduler@python-for-bigquery.iam.gserviceaccount.com in my case)?

**Comment by MarkEdmondson1234** [comment]
Can you try the examples on the website as is, in a clean R session? The script you show above sets lots of other things and is not a clean example. You don’t need to load googleComputeEngineR for example, or scopes. I would also check your environment  files as I suspect you have one that is overwriting your R session.

**Comment by MarkEdmondson1234** [comment]
And can you try with a new service email, as laid out in the setup guide on the website, giving it the exact roles it describes. I followed this guide myself when setting it up again and it works as expected.

**Comment by axel-analyst** [comment]
Hi Mark, yes, scopes with different methods of auth for several packages made the conflict. Thanks your advice helped.

However, the function cr_deploy_r() still does not work:) 
```
2020-02-26 12:59:42> Request Status Code: 400
2020-02-26 12:59:42> API returned error: invalid build: invalid .steps field: build step 0 arg 2 too long (max: 4000)
2020-02-26 12:59:42> No retry attempted: invalid build: invalid .steps field: build step 0 arg 2 too long (max: 4000)
Error: API returned: invalid build: invalid .steps field: build step 0 arg 2 too long (max: 4000)
```
I tried to split the code into chunks (like rscript<-c("a<-1+1","b<-a+3")), but the error is still there. How to deal with this? The script is mostly 'for' cycle to download data from Search Console and import them into Big Query.

**Comment by MarkEdmondson1234** [comment]
Glad its a new error at least :)  It sounds like you are running into the hard limit on build files, which is discussed in this issue on ways to work around it: https://github.com/MarkEdmondson1234/googleCloudRunner/issues/45 - will close this one now the original issue is solved.
