### ISSUE TITLE
Scheduling built objects sometimes not working

### ISSUE THREAD

**Issue by MarkEdmondson1234** [MarkEdmondson1234/googleCloudRunner#47]
Some trouble in parsing between built and to build objects - e.g. a valid build can not be scheduled from its build object.  

Work-around is to use `cr_build_make()` to construct the build object for `cr_build_schedule_http()` but its nicer the first way. 

Seems to create invalid yaml - at least catch this error:

```yaml
steps:
  name:
    - gcr.io/iih-sdadsadad/searchmetricsr:latest
    - gcr.io/cloud-builders/gsutil
    - gcr.io/cloud-builders/gcloud
  env:
    - - SEARCHMETRICS_KEY=sdadad
      - SEARCHMETRICS_SECRET=sdadadadads
  args:
    - - Rscript
      - -e
      - |-
        o <- searchMetricsR::sm_organic_seoviz(c('ikea.com','iasdadasd.com'))
        names(o) <- gsub("[^a-zA-Z0-9]","", names(o))
        dir.create("export")
        jsonlite::write_json(o, paste0('/workspace/export/sm-export.json'))
    - - -m
      - cp
      - -r
      - /workspace/export/*.json
      - gs://iih-sdsaasdasd/searchmetrics/
    - - --location=EU
      - load
      - --autodetect
      - --replace
      - --source_format=NEWLINE_DELIMITED_JSON
      - tests.sm_organic_viz
      - gs://iih-sasdasdadsa/searchmetrics/sm-export.json
  timing:
    startTime:
      - '2020-03-05T13:40:08.132698194Z'
      - '2020-03-05T13:40:34.002464840Z'
      - '2020-03-05T13:40:36.875253529Z'
    endTime:
      - '2020-03-05T13:40:34.002378956Z'
      - '2020-03-05T13:40:36.875174275Z'
      - '2020-03-05T13:40:40.764863136Z'
  status:
    - SUCCESS
    - SUCCESS
    - SUCCESS
  pullTiming:
    startTime:
      - '2020-03-05T13:40:08.132698194Z'
      - '2020-03-05T13:40:34.002464840Z'
      - '2020-03-05T13:40:36.875253529Z'
    endTime:
      - '2020-03-05T13:40:28.876002232Z'
      - '2020-03-05T13:40:34.010401596Z'
      - '2020-03-05T13:40:36.879042493Z'
  entrypoint:
    - .na.character
    - .na.character
    - bq
```

**Comment by justinjm** [comment]
Hi Mark,

Thank you for posting this issue, was scratching my head yesterday until I came across this! Please let me know if I could help troubleshoot or share more of my code that resulted in not being able to schedule the build from a build object returned by `cr_build()` 

For a bit more context, my `cr_build_yaml()` is an expanded version of this use case: [Polygot Cloud Builds - integrating R code with other languages](https://code.markedmondson.me/googleCloudRunner/articles/usecases.html#polygot-cloud-builds-integrating-r-code-with-other-languages) 


For anyone else that comes across this, here's the code I used/the workaround Mark mentioned above: 

```r
repo_source <- cr_build_source(RepoSource("repository-name",
                                          branchName="master"))

raw_yaml <- cr_build_yaml(
  steps = c(
    cr_buildstep(...
    ),
    ...
  ),
  ...
)

build_object <- cr_build_make(raw_yaml, 
                              timeout = 3600, 
                              source = repo_source)

build_target <- cr_build_schedule_http(build_object) 

cr_schedule("0 5 * * *", 
            name = "daily_job",
            httpTarget = build_target)
```

**Comment by MarkEdmondson1234** [comment]
No worries!  Yes I need to parse the built object so it extracts the build you send in, to enable one to chain these things together.

**Comment by justinjm** [comment]
That would be awesome! The workaround above worked perfectly and is no problem for me in the interim. 

Thank you for all the hard work on this package, it's been invaluable in my latest projects and feels like I'm only scratching the surface :)

**Comment by MarkEdmondson1234** [comment]
`cr_build_status()` should have been returning a valid Cloud Build object but was only setting the class of the returned object which confused things a lot, fixed this and should be better long term
