### ISSUE TITLE
Time Zone Field

### ISSUE THREAD

**Issue by samterfa** [MarkEdmondson1234/googleCloudRunner#49]
Thank you for this amazing package!

I am hoping to set the time zone for my scheduled jobs. The cr_schedule() function relies on the Job() function to create a job object, and that function does admit timeZone as a field. Would you be willing to modify cr_schedule() to admit timeZone as a variable which would then be passed to Job() inside it? Or perhaps you could pass in an environmental variable as default such as CR_TIME_ZONE? I've used assignInNameSpace to pass my own version of cr_schedule() with my default time zone, which works fine for the time being. I apologize if this is covered in the yml specifications or elsewhere; I have been using cr_deploy_gadget() for easy job deployment so far.

Thank you!

**Comment by MarkEdmondson1234** [comment]
Thanks for the feedback! Sure that sounds doable, do you have an example on how you do it to help me implement it? A new CRAN release soon to cover some bug updates so hopefully it can be included in that.

**Comment by samterfa** [comment]
Given how you've structured these functions, I would... 

1. Modify cr_schedule like so:

function (name, schedule = NULL, httpTarget = NULL, description = NULL, 
    overwrite = FALSE, region = cr_region_get(), projectId = cr_project_get(), timeZone = cr_time_zone_get()) 
{
    assert_that(is.string(region))
    stem <- "https://cloudscheduler.googleapis.com/v1"
    the_name <- contruct_name(name = name, region = region, project = projectId)
    job <- Job(schedule = schedule, name = the_name, httpTarget = httpTarget, 
        description = description, timeZone = timeZone)
    if (overwrite) {
        scheds <- cr_schedule_list(region = region, projectId = projectId)
        if (the_name %in% scheds$name) {
            myMessage("Overwriting schedule job: ", name, level = 3)
            the_url <- paste0(stem, "/", the_name)
            updateMask <- rmNullObs(list(schedule = schedule, 
                httpTarget = httpTarget, description = description))
            f <- gar_api_generator(the_url, "PATCH", data_parse_function = parse_schedule, 
                pars_args = list(updateMask = paste(names(updateMask), 
                  collapse = ",")))
        }
    }
    else {
        assert_that(is.string(schedule))
        the_url <- sprintf("%s/projects/%s/locations/%s/jobs", 
            stem, projectId, region)
        f <- gar_api_generator(the_url, "POST", data_parse_function = parse_schedule)
    }
    stopifnot(inherits(job, "gar_scheduleJob"))
    o <- f(the_body = job)
    if (o$state == "UPDATE_FAILED") {
        o <- retry_update_failed(job, f)
    }
    o
}

2. I would add the function cr_time_zone_set() defined as:

function (timeZone = "UTC") 
{
    .cr_env$timeZone <- timeZone
    myMessage("Time zone set to ", .cr_env$timeZone, level = 3)
    .cr_env$timeZone
}

3. I would add the function cr_time_zone_get() defined as:

function () 
{
    if (!is.null(.cr_env$timeZone)) {
        return(.cr_env$timeZone)
    }
    if (Sys.getenv("CR_TIME_ZONE") != "") {
        .cr_env$timeZone <- Sys.getenv("CR_TIME_ZONE")
    }
    if (is.null(.cr_env$timeZone)) {
        stop("No time zone set - use cr_time_zone_set() or env arg CR_TIME_ZONE", 
            call. = FALSE)
    }
    .cr_env$timeZone
}

4. Finally, I'd update the documentation for .Renviron to include the new environment parameter CR_TIME_ZONE.

I realize this probably would be better with a pull request, but this involves more than just a merge.

Thanks again!

**Comment by MarkEdmondson1234** [comment]
I wonder if there is a more general R setting like locale that sets the local time zone.

**Comment by samterfa** [comment]
[Sys.timezone()](https://stat.ethz.ch/R-manual/R-devel/library/base/html/timezones.html) returns the correct timezone for me so that's an option.

**Comment by MarkEdmondson1234** [comment]
I think this should work now, give it a go?  It uses Sys.timezone() by default, or you can supply your own.  Install dev version from github to try it

```r
#' # By default will use the timezone as specified by Sys.timezone() - change
#' # this by supplying it directly
cr_schedule("timzone-utc", "12 2 * * *", timeZone = "UTC")
```

**Comment by samterfa** [comment]
The timezone was pulled successfully! Thanks for the quick work!
