### ISSUE TITLE
Docker Image/Container Path Prepended with "rocker/"

### ISSUE THREAD

**Issue by samterfa** [MarkEdmondson1234/googleCloudRunner#50]
Running cr_deploy_r() with the r_image field populated with an R Docker image not hosted on rocker causes "rocker/" to be prepended to the Docker container path.

Example:
`cr_deploy_r(r = 'TestScript.R', r_image = 'myDockerAccount/myRcontainer')` tries to pull "rocker/myDockerAccount/myRcontainer" instead of "myDockerAccount/myRcontainer" from Docker.

The cause looks to be the cr_buildstep_r() function which passes in a Prefix parameter which defaults to "rocker/". The heart of the matter is that cr_deploy_r() doesn't pass in or write over the Prefix parameter when calling cr_buildstep_r() in the following line of code:

`build <- cr_build_yaml(steps = c(pre_steps, cr_buildstep_r(r = r, name = r_image, id = run_name), post_steps))`

I'm not sure how often the "rocker/" prefix comes in handy for you, but if it were up to me, I would get rid of it or set it to "" by default. But you have a much better idea of its utility.

I can make a pull request if desired.

Thanks, and again, awesome package!

**Comment by MarkEdmondson1234** [comment]
If you do 

```r
cr_deploy_r(r = 'TestScript.R', r_image = 'myRcontainer', prefix = 'myDockerAccount/')
``` 

...does it fix it?  That is at least how it is intended to work.

**Comment by samterfa** [comment]
Then you get the error "unused argument (prefix = "")". prefix isn't a parameter for cr_deploy_r, and there isn't the ellipsis ... either.

**Comment by MarkEdmondson1234** [comment]
Ok, need to fix that it can pass it through to `cr_buildstep()`

**Comment by MarkEdmondson1234** [comment]
This should be fixed now? I was suppressing prefix in `cr_buildstep_r()` by accident

**Comment by MarkEdmondson1234** [comment]
Oh sorry thats for the buildstep, not deploy - not fixed yet

**Comment by MarkEdmondson1234** [comment]
Ok `cr_deploy_r()` now passed through to `cr_buildstep_r()` in the dev version on GitHub.

**Comment by samterfa** [comment]
Thanks for the quick work! cr_deploy_r() does pass the prefix parameter nicely. 

One further issue is that the awesome deploy gadget Shiny app does not pass or parse the prefix given when changing the default "R docker image" from "rocker/verse" to something else, which was how I stumbled onto the issue in the first place. I should have mentioned that...

Thank you!

**Comment by MarkEdmondson1234** [comment]
I think that is fixed now, can you test it?

**Comment by samterfa** [comment]
Tested. The / ends up missing between the account name and container name. e.g. samterfamyRcontainer instead of samterfa/myRcontainer.

cr_deploy_gadget should change the line `prefix = image_split[[1]]` to something like `prefix = paste0(image_split[[1]], '/')`. Or you could add a check for the '/' in the cr_buildstep_r or cr_buildstep functions?

**Comment by MarkEdmondson1234** [comment]
Thanks!  I think thats got it now - did as you suggested

**Comment by samterfa** [comment]
It worked great, thanks!
