### ISSUE TITLE
Set a default PORT for plumber API to cover local testing

### ISSUE THREAD

**Issue by samterfa** [MarkEdmondson1234/googleCloudRunner#66]
If you run the Quickstart Plumber API via Docker for local testing, you will receive an error `Error in if (port == 0) { : missing value where TRUE/FALSE needed
Calls: <Anonymous> -> findPort
Execution halted` because there isn't a system environment variable PORT configured by default. Adding something like `if(Sys.getenv('PORT') == '') Sys.setenv(PORT = 8000)` to the top of the example will allow local testing before deploying the API to Cloud Run. Thanks for the great package!

**Comment by MarkEdmondson1234** [comment]
Thank you!  Yes I don't do much local testing for these as I prefer to solve any deployment issues up front but makes sense to have working examples locally too.
