### ISSUE TITLE
cr_deploy_docker and default tag problem

### ISSUE THREAD

**Issue by MLud** [MarkEdmondson1234/googleCloudRunner#67]
Running without tag option set strange tag for image, while in cr_buildstep_r i have to use an image with tag.
Quick solution is use tag='latest'

**Comment by MarkEdmondson1234** [comment]
Its probably picking up the default of the $BUILD_ID of the Cloud Build, but that should not be used for `cr_buildstep_r()` if you are supplying your own.  As you say may change the default tag to 'latest' although in general I recommend to always specify a tag.

**Comment by MarkEdmondson1234** [comment]
You can now specify multiple tags, which means you can use "latest" and "$BUILD_ID" which keeps convenience but also reproducibility of images.
