### ISSUE TITLE
cr_schedule() creates a schedule for cloud build which doesn't have permission

### ISSUE THREAD

**Issue by jrpeck1989** [MarkEdmondson1234/googleCloudRunner#71]
After running `build <- cr_build_make("my-yaml.yaml")`, and then `cr_schedule(name = "bq_r_test_schedule", schedule = "*/2 * * * *", httpTarget = cr_build_schedule_http(build))` this creates a cloud schedule that is pointed at the build, but when the schedule runs it erros with "PERMISSION_DENIED"

Cloud Schedule log:
`{
insertId: "1snmqroftlpeaj"
jsonPayload: {
jobName: "projects/project_name/locations/us-central1/jobs/bq_r_test_schedule"
targetType: "HTTP"
status: "PERMISSION_DENIED"
@type: "type.googleapis.com/google.cloud.scheduler.logging.AttemptFinished"
url: "https://cloudbuild.googleapis.com/v1/projects/project_name/builds"
}
httpRequest: {0}
resource: {
type: "cloud_scheduler_job"
labels: {
job_id: "bq_r_test_schedule"
project_id: "project_name"
location: "us-central1"
}
}
timestamp: "2020-05-24T20:30:00.726478644Z"
severity: "ERROR"
logName: "projects/project_name/logs/cloudscheduler.googleapis.com%2Fexecutions"
receiveTimestamp: "2020-05-24T20:30:00.726478644Z"
}`

**Comment by MarkEdmondson1234** [comment]
Can you 1) delete any existing schedules 2) build the working build 3) set options(googleAuthR.verbose=2) 4) send the build you know works up for schedule again.

**Comment by jrpeck1989** [comment]
After deleting the existing schedules, re-doing the build, and setting the options to verbose, this is the console output

`> options(googleAuthR.verbose = 2)
> cr_schedule("*/2 * * * *", name = "bq_upload_testv2", httpTarget = cr_build_schedule_http(cr_build("r-docker/r-docker.yaml")), region = "us-central1")
2020-05-26 09:49:40> Token exists.
2020-05-26 09:49:40> Request: https://cloudbuild.googleapis.com/v1/projects/project_id/builds/
2020-05-26 09:49:40> Body JSON parsed to: {"steps":[{"name":"eu.gcr.io/project_id/docker_bq_upload_bigqueryr2"}]}
i 2020-05-26 09:49:42 > Cloud Build started - logs: 
 https://console.cloud.google.com/cloud-build/builds/27f80a8f-8340-46ff-b010-01957243825f?project=122997258217
2020-05-26 09:49:42> Token exists.
2020-05-26 09:49:42> Request: https://cloudbuild.googleapis.com/v1/projects/project_id/builds/27f80a8f-8340-46ff-b010-01957243825f/
2020-05-26 09:49:42> Token exists.
2020-05-26 09:49:42> Request: https://cloudscheduler.googleapis.com/v1/projects/project_id/locations/us-central1/jobs/
2020-05-26 09:49:42> Body JSON parsed to: {"httpTarget":{"body":"eyJpZCI6IjI3ZjgwYThmLTgzNDAtNDZmZi1iMDEwLTAxOTU3MjQzODI1ZiIsInN0YXR1cyI6IlFVRVVFRCIsImNyZWF0ZVRpbWUiOiIyMDIwLTA1LTI2VDA4OjQ5OjQxLjE1MTI3ODIwM1oiLCJzdGVwcyI6W3sibmFtZSI6ImV1Lmdjci5pby9tc21yYW5raW5ncy9kb2NrZXJfYnFfdXBsb2FkX2JpZ3F1ZXJ5cjIifV0sInRpbWVvdXQiOiI2MDBzIiwicHJvamVjdElkIjoibXNtcmFua2luZ3MiLCJsb2dzQnVja2V0IjoiZ3M6Ly8xMjI5OTcyNTgyMTcuY2xvdWRidWlsZC1sb2dzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsIm9wdGlvbnMiOnsibG9nZ2luZyI6IkxFR0FDWSJ9LCJsb2dVcmwiOiJodHRwczovL2NvbnNvbGUuY2xvdWQuZ29vZ2xlLmNvbS9jbG91ZC1idWlsZC9idWlsZHMvMjdmODBhOGYtODM0MC00NmZmLWIwMTAtMDE5NTcyNDM4MjVmP3Byb2plY3Q9MTIyOTk3MjU4MjE3IiwicXVldWVUdGwiOiIzNjAwcyJ9","oauthToken":{"serviceAccountEmail":"r-docker-container-service-acc@project_id.iam.gserviceaccount.com"},"uri":"https://cloudbuild.googleapis.com/v1/projects/project_id/builds","httpMethod":"POST"},"timeZone":"Europe/London","name":"projects/project_id/locations/us-central1/jobs/bq_upload_testv2","schedule":"*/2 * * * *"}
==CloudScheduleJob==
name:  projects/project_id/locations/us-central1/jobs/bq_upload_testv2 
state:  ENABLED 
httpTarget.uri:  https://cloudbuild.googleapis.com/v1/projects/project_id/builds 
httpTarget.httpMethod:  POST 
userUpdateTime:  2020-05-26T08:49:45Z 
schedule:  */2 * * * * 
timezone:  Europe/London 
Warning message:
In readLines(file) :
  incomplete final line found on 'r-docker/r-docker.yaml'`

This still creates a schedule that has "PERMISSION_DENIED" and fails to run the build on my schedule or when manually triggered.

**Comment by jrpeck1989** [comment]
When doing 

`build <- cr_build_make(yaml = "my_yaml.yaml")
build_object <- cr_build_schedule_http(build = build)
cr_schedule(name = "sessions_to_bq", schedule = "0 6 * * *", httpTarget = build_object)`

instead of 

`build <- cr_build(yaml = "dockerise-scripts/my_yaml.yaml")
cr_schedule(name = "sessions_to_bq", schedule = "0 6 * * *", httpTarget = build)`

I notice that in the Cloud Scheduler itself, the `body` object is very different. 

`cr_build_make` : 
`{"steps":[{"name":"eu.gcr.io/project_id/my_image"}]}`

`cr_build` : 
`{
	"id": "136f6549-05c5-4410-a8eb-1974ebd68604",
	"status": "QUEUED",
	"createTime": "2020-05-26T16:28:15.913138203Z",
	"startTime": "2020-05-26T16:28:16.978965312Z",
	"finishTime": "2020-05-26T16:29:17.469146Z",
	"results": {
		"buildStepImages": "",
		"buildStepOutputs": ""
	},
	"steps": [{
		"name": "eu.gcr.io/project_id/my_image",
		"timing": {
			"startTime": "2020-05-26T16:28:19.713571388Z",
			"endTime": "2020-05-26T16:29:16.872511434Z"
		},
		"status": "SUCCESS",
		"pullTiming": {
			"startTime": "2020-05-26T16:28:19.713571388Z",
			"endTime": "2020-05-26T16:29:12.966342204Z"
		}
	}],
	"timeout": "600s",
	"projectId": "project_id",
	"logsBucket": "gs://123456.cloudbuild-logs.googleusercontent.com",
	"sourceProvenance": {},
	"options": {
		"logging": "LEGACY"
	},
	"logUrl": "https://console.cloud.google.com/cloud-build/builds/136f6549-05c5-4410-a8eb-1974ebd68604?project=123456",
	"timing": {
		"BUILD": {
			"startTime": "2020-05-26T16:28:18.902426866Z",
			"endTime": "2020-05-26T16:29:16.872551800Z"
		}
	},
	"queueTtl": "3600s"
}`

Both are still getting `PERMISSION_DENIED` but this might be important?

JP

**Comment by MarkEdmondson1234** [comment]
The result of a `cr_build()` (`built`?) won't work yet due to issue https://github.com/MarkEdmondson1234/googleCloudRunner/issues/47

Lets work with a minimal example to check the scheduler - the below if doesn't work means its the scheduler setup and nothing to do with the script:

```r
# create an r script that will echo the time
the_build <- cr_build_yaml(cr_buildstep_r("cat(Sys.time())"))

# construct a Cloud Build API call to call that build
build_call <- cr_build_schedule_http(the_build)

# schedule the API call
cr_schedule("test1", "1 * * * *", httpTarget = build_call)

# you should return a scheduler object
test_schedule <- cr_schedule_get("test1")
```

Then can you check the value of `test_schedule$httpTarget` which should look similar to below:

```r
$uri
[1] "https://cloudbuild.googleapis.com/v1/projects/my-project/builds"

$httpMethod
[1] "POST"

$headers
$headers$`Content-Type`
[1] "application/octet-stream"

$headers$`User-Agent`
[1] "Google-Cloud-Scheduler"


$body
[1] "eyJzdGVwcyI6W3sibmFtZSI6InJvY2tlci9yLWJhc2UiLCJhcmdzIjpbIlJzY3JpcHQiLCItZSIsImNhdChTeXMudGltZSgpKSJdfV19"

$oauthToken
$oauthToken$serviceAccountEmail
[1] "goooglecloudrunner@my-project.iam.gserviceaccount.com"

$oauthToken$scope
[1] "https://www.googleapis.com/auth/cloud-platform"
```

In particular see if the `test_schedule$httpTarget$oauthToken$serviceAccountEmail` is what you expect, and that email has the roles/permissions necessary (Cloud Build as a minimum)

**Comment by MarkEdmondson1234** [comment]
Also, run `cr_setup_tests()` to run some tests and see if they all work. 

```r
cr_setup_test()
#ℹ Perform deployments to test your setup is working. Takes around 5mins.  ESC or 0 to skip.
#Select which deployments to test 
#
#1: All tests
#2: Cloud Build - Docker
#3: Cloud Run - plumber API with Pub/Sub
#4: Cloud Build - R script
#5: Cloud Scheduler - R script
```

**Comment by MarkEdmondson1234** [comment]
And looking back, I think you can skip a lot of the above now you have your image if you use `cr_deploy_r()` which will build the scheduler for you

https://code.markedmondson.me/googleCloudRunner/reference/cr_deploy_r.html

**Comment by MarkEdmondson1234** [comment]
The issue was the lack of a Cloud Scheduler Service Agent service account present in an older GCP project. https://cloud.google.com/scheduler/docs/http-target-auth

Should be fixed if users use `cr_setup()` via https://github.com/MarkEdmondson1234/googleCloudRunner/issues/73
