### ISSUE TITLE
Docker container - Specify version of R package to install?

### ISSUE THREAD

**Issue by j450h1** [MarkEdmondson1234/googleCloudRunner#80]
For whatever reason, in my docker container, the latest version of googleAnalytics is the one hosted on MRAN - 0.7.1
(https://mran.microsoft.com/package/googleAnalyticsR)

```
RUN ["install2.r", "googleAnalyticsR"]
```

What is your preferred method of installing a specific version of an R package version? This is what I got so far, but feel like there should be a simpler way

```
# install R Packages
RUN R -e "install.packages('devtools', repos = c(CRAN = 'https://cloud.r-project.org'))"
RUN R -e "devtools::install_version('googleAnalyticsR', version = '0.8.0', dependencies = T, force = T)"
```

**Comment by j450h1** [comment]
I found one of your old issues on containerit:

```
RUN ["install2.r", "-r 'https://cloud.r-project.org'", "httpuv", "assertthat", "here", "dplyr", "gargle", "googleAuthR", "googleAnalyticsR", "googleCloudStorageR", "bigQueryR"]
```
That might do the trick to download the latest package version from CRAN instead of MRAN? But would still be nice to know the method to install a specific version.

**Comment by MarkEdmondson1234** [comment]
I think that is the way to do it, as you do in the first issue.

I have started to build docker images of the packages for this reason to always have a current version, for example googleAnalyticsR has `gcr.io/gcer-public/googleanalyticsr:latest` from https://github.com/MarkEdmondson1234/googleAnalyticsR/blob/master/Dockerfile

I tend to install the GitHub version to get the latest so via `&& installGithub.r MarkEdmondson1234/googleAnalyticsR` but of course that is not stable.  I guess the issue of old CRAN versions is only temporary and is an issue for about a week after release, until MRAN etc. updates.
