### ISSUE TITLE
jwt authentication failure: 401 http status

### ISSUE THREAD

**Issue by optimaldecisiondynamics** [MarkEdmondson1234/googleCloudRunner#99]
Hi Mark,

Thank you for all your incredible work to make R in the cloud accessible!  I was thrilled to discover your blog posts and packages, and I'm excited to tinker with them in 2021!

I hope to try out `googleCloudRunner`, but have had issues authenticating with a jwt.  I have read your tutorials and documentation; my apologies if I've missed something.  

My goal is to connect to an authenticated API on Google Cloud Run from a shiny app.

Note that I did not use `googleCloudRunner` to deploy the service (a plumber API), but when I remove authentication the API call indeed works via the `httr` package.

When I run `gcr_token <- cr_jwt_create(the_url = api_url,
                           service_json = Sys.getenv("GCE_AUTH_FILE"))` there is no error; `gcr_token` is a long string.

Though when I use the token I get a 401 error; i.e., I am unable to authenticate to my service.  Is it a requirement to deploy via `googleCloudRunner` for jwt authentication to work?  Or is use of the package for token creation and authentication to an existing service a valid use case?

**Context:**
- I am on a Windows machine.  I am unsure whether this [issue](https://github.com/MarkEdmondson1234/googleCloudRunner/issues/70) is related.
- I have had issues with `cr_setup()`, which took several restarts of R.  During setup I received the error `Could not read details from client ID file - is it the right one?  Need a clientId to be set before configuring further`  Services are enabled as you advise in your tutorials.
- Running `cr_setup()` also gave the following error for configuring the cloud build service account: `Error: parse error: premature EOF (right here) ------^`
- Though when I run `cr_setup()` now it appears to work.

Any help or advice you can provide would be greatly appreciated.

**Comment by MarkEdmondson1234** [comment]
Thanks for trying it out :)

You need a valid json key file to point to for the `service_json` argument as that is used for creating the token - it should be the file for the service email that has Cloud Run Invoker via the IAM for Cloud Run.  I don't think it needs to be deployed via googleCloudRunner to use it and an existing one will work.

On successful setup via `cr_setup()` then `Sys.getenv("GCE_AUTH_FILE")` should be pointing at a valid json key (that is for the Cloud Run invoker email above).  If you want to skip that then make sure you download a valid one yourself, and point to its file location in your call - you also need the URL of the Cloud Run app [see website example](https://code.markedmondson.me/googleCloudRunner/articles/usecases.html#calling-the-private-plumber-api-with-a-jwt)

```r
jwt <- cr_jwt_create(the_url, service_json = "your-key-file.json")

# needs to be recreated every 60mins
token <- cr_jwt_token(jwt, the_url)

# call Cloud Run with token using httr call
library(httr)
res <- cr_jwt_with_httr(
  GET("https://parallel-cloudrun-ewjogewawq-ew.a.run.app/"),
  token)
content(res)
```

The `cr_jwt_with_httr()` function adds the token to the httr call, you can examine that on what it does if you want to spin your own. 

It is normal to need to restart R and rerun `cr_setup()` to get through all the setup steps.  It looks like you did not use the right client ID json file in that setup initially (note this is the client, not the auth key)

**Comment by optimaldecisiondynamics** [comment]
Thanks for your lightning fast response!

Ah, my mistake in that there are **2 functions** required to generate the token.  My apologies; I thought that `cr_jwt_create()` created the token.  I passed the result into `cr_jwt_token()` as you do and it worked!

**Quick Follow-up Questions:**
- I see that `cr_jwt_token()` must be recreated every 60 minutes, but **NOT** `cr_jwt_create()`?  Meaning in a shiny application I could put `jwt <- cr_jwt_create(the_url, service_json = "your-key-file.json")` in global scope (outside `ui` or `server`), and `token <- cr_jwt_token(jwt, the_url)` within `observeEvent()`?  If I'm understanding correctly, this means `jwt` can be created once and the token itself is recreated every time a button is clicked.  That way the observer can trigger the API.
- If I wanted to deploy the shiny app on shinyapps.io is it sufficient to pass environmental variables after a successful run of `cr_setup()`? (see [here](https://stackoverflow.com/questions/59149603/passing-environmental-variables-to-shinyapps-io))

Thanks again and happy new year!

**Comment by MarkEdmondson1234** [comment]
Yes the token is signed with the JWT you create in the first step that is static, and could be done in global.R .  You have to set a time-limit for auth tokens so I chose 60mins as thats fairly typical - the relevant code is here:

https://github.com/MarkEdmondson1234/googleCloudRunner/blob/84db9106608e498ae36d8535e70ef82ab0ae173b/R/jwt-requests.R#L61-L68

You can send up .Renviron files with Shiny apps that can be read on shinyapps.io or other Shiny hosting solutions, or hard wire them in your code, whichever is easiest.

**Comment by MarkEdmondson1234** [comment]
e.g. you need to call `cr_jwt_create()` then `cr_jwt_token()` every 60 mins

**Comment by MarkEdmondson1234** [comment]
They are a bit new so a bit raw, I think eventually the code above will end up in one function for convenience.

**Comment by optimaldecisiondynamics** [comment]
Makes sense!  New and raw, but incredible functionality for the R community! :)

It seems I would only use `jwt_claim()` if I wanted to change the expiry duration, otherwise it's the default 60 minutes (works for me) and there is no additional configuration?

Is there harm in calling `cr_jwt_create()` then `cr_jwt_token()` more frequently than every 60 minutes?  E.g., within an observer anytime a button is clicked?  My thinking is that way the shiny app will always be able to authenticate to Google Cloud Run.  Though I'm new to the cloud and tokens, and unsure whether a token must be retained for 60 minutes.

Hope I'm not asking too many questions.  Thanks again!

**Comment by MarkEdmondson1234** [comment]
No harm calling it more often, just that cr_jwt_token() is an extra HTTP API call so probably don't want to do it every request to your Cloud Run

**Comment by optimaldecisiondynamics** [comment]
Great, thanks!  I appreciate all your help.  I'll close this issue as I'm all set.
